version: '3.9'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/kotlin-testing

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
